In [1]:
import numpy as np 
import pandas as pd

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on="title")

In [6]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

What to remain

In [7]:
#genres
#id
#keywords
#title
#overview
#production_companies
#cast
#crew
#release dates

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew','release_date']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015-10-26
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012-07-16
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012-03-07

Data Preprocessing

In [9]:
#inoreder to merge all except movie_id and title
#we need to preprocess the data inside each column to a mergable and understandable data and delete missing data

In [10]:
movies.isnull().sum()

movie_id        0
title           0
overview        3
genres          0
keywords        0
cast            0
crew            0
release_date    1
dtype: int64

In [11]:
movies.dropna(inplace=True)
movies = movies.reset_index(drop=True)

In [12]:
movies.isnull().sum()

movie_id        0
title           0
overview        0
genres          0
keywords        0
cast            0
crew            0
release_date    0
dtype: int64

In [13]:
movies.duplicated().sum()

0

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import ast

In [16]:
def convert(obj):
    names = []
    for i in ast.literal_eval(obj):
        names.append(i['name'])
    return names

In [17]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4800                        [Action, Crime, Thriller]
4801                                [Comedy, Romance]
4802               [Comedy, Drama, Romance, TV Movie]
4803                                               []
4804                                    [Documentary]
Name: genres, Length: 4805, dtype: object

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies = movies[movies['genres'].apply(lambda x : len(x)>0)]
movies = movies.reset_index(drop=True)

In [20]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4773                              [Foreign, Thriller]
4774                        [Action, Crime, Thriller]
4775                                [Comedy, Romance]
4776               [Comedy, Drama, Romance, TV Movie]
4777                                    [Documentary]
Name: genres, Length: 4778, dtype: object

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015-10-26
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012-07-16
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012-03-07

In [22]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4773                                                   []
4774    [united states–mexico barrier, legs, arms, pap...
4775                                                   []
4776    [date, love at first sight, narration, investi...
4777            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4778, dtype: object

In [23]:
movies['keywords'] = movies['keywords'].apply(convert)

In [24]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4773                                                   []
4774    [united states–mexico barrier, legs, arms, pap...
4775                                                   []
4776    [date, love at first sight, narration, investi...
4777            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4778, dtype: object

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015-10-26
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012-07-16
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012-03-07

In [26]:
def convert_cast(obj):
    names = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 5:
            names.append(i['character'])
            counter += 1
        else:
            break    
    return names

In [27]:
movies['cast'].apply(convert_cast)

0       [Jake Sully, Neytiri, Dr. Grace Augustine, Col...
1       [Captain Jack Sparrow, Will Turner, Elizabeth ...
2              [James Bond, Blofeld, Madeleine, M, Lucia]
3       [Bruce Wayne / Batman, Alfred Pennyworth, Jame...
4       [John Carter, Dejah Thoris, Sola, Tars Tarkas,...
                              ...
4773                                                   []
4774    [El Mariachi, Bigotón, Mauricio (Moco), Azul, ...
4775               [Buzzy, Linda, Marsha, Katie, Vanessa]
4776    [Oliver O’Toole, Shane McInerney, Rita Haywith...
4777        [Herself, Himself, Himself, Himself, Himself]
Name: cast, Length: 4778, dtype: object

In [28]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain Jack Sparrow, Will Turner, Elizabeth ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[James Bond, Blofeld, Madeleine, M, Lucia]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015-10-26
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012-07-16
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012-03-07

In [30]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [31]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Jake Sully, Neytiri, Dr. Grace Augustine, Col...",[James Cameron],2009-12-10
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski],2007-05-19
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[James Bond, Blofeld, Madeleine, M, Lucia]",[Sam Mendes],2015-10-26
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Bruce Wayne / Batman, Alfred Pennyworth, Jame...",[Christopher Nolan],2012-07-16
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John Carter, Dejah Thoris, Sola, Tars Tarkas,...",[Andrew Stanton],2012-03-07

In [33]:
movies['release_date'] = pd.to_datetime(movies['release_date']).dt.year

In [34]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [35]:
movies['overview'] = movies['overview'].apply(lambda x:x.split()) # convert overview into a list of words

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Jake Sully, Neytiri, Dr. Grace Augustine, Col...",[James Cameron],2009
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski],2007
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[James Bond, Blofeld, Madeleine, M, Lucia]",[Sam Mendes],2015
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Bruce Wayne / Batman, Alfred Pennyworth, Jame...",[Christopher Nolan],2012
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John Carter, Dejah Thoris, Sola, Tars Tarkas,...",[Andrew Stanton],2012

In [37]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [38]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[JakeSully, Neytiri, Dr.GraceAugustine, Col.Qu...",[JamesCameron],2009
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[CaptainJackSparrow, WillTurner, ElizabethSwan...",[GoreVerbinski],2007
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[JamesBond, Blofeld, Madeleine, M, Lucia]",[SamMendes],2015
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[BruceWayne/Batman, AlfredPennyworth, JamesGor...",[ChristopherNolan],2012
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[JohnCarter, DejahThoris, Sola, TarsTarkas, Ta...",[AndrewStanton],2012

In [39]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [40]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[JakeSully, Neytiri, Dr.GraceAugustine, Col.Qu...",[JamesCameron],2009,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[CaptainJackSparrow, WillTurner, ElizabethSwan...",[GoreVerbinski],2007,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[JamesBond, Blofeld, Madeleine, M, Lucia]",[SamMendes],2015,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[BruceWayne/Batman, AlfredPennyworth, JamesGor...",[ChristopherNolan],2012,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[JohnCarter, DejahThoris, Sola, TarsTarkas, Ta...",[AndrewStanton],2012,"[John, Carter, is, a, war-weary,, former, mili..."

In [41]:
new_df = movies[['movie_id','title','tags','genres','release_date']]

In [42]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\hp\AppData\Local\Temp\ipykernel_7476\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [43]:
new_df.head()

,movie_id,title,tags,genres,release_date
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]",2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]",2007
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]",2015
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]",2012
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]",2012

In [44]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d JakeSully Neytiri Dr.GraceAugustine Col.Quaritch TrudyChacon JamesCameron'

In [45]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\hp\AppData\Local\Temp\ipykernel_7476\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [46]:
new_df.head()

,movie_id,title,tags,genres,release_date
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di...","[Action, Adventure, Fantasy, ScienceFiction]",2009
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]",2007
2,206647,Spectre,a cryptic message from bond’s past sends him o...,"[Action, Adventure, Crime]",2015
3,49026,The Dark Knight Rises,following the death of district attorney harve...,"[Action, Crime, Drama, Thriller]",2012
4,49529,John Carter,"john carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]",2012

Text Vectorization

In [47]:
# A score is to be calcualted to check the similarity between the texts
# Like no of same words
# But this is not that simple or efficient so vectorization of text is used

In [48]:
# In text vectorization, text is converted into vertors using the method bag of words another method is there as well tfidf but here we use the first one
# all tags for a movie will be concatenated and most used words are chosen out of them

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [50]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [51]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [52]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [ ]:
# we can observe that we get some similar words 
# so we combine all the similar words to make a single word
# this is done using a library called "nltk" which is a natural language processing libarary
# it gives root word for every word like loving,loved -> love

In [55]:
import nltk

In [56]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [57]:
# function to convert text into their stem forms
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [58]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\hp\AppData\Local\Temp\ipykernel_7476\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [59]:
# do vectorization again with updated tags list

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [61]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [62]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [63]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [64]:
# now we have vectors for each movie with each vector is of length 5000 which is most used 5000 words
# now we need to find the distances of vectors from each other
# but vectors as dimensions go higher euclidean distances fail often 
# therefore we find the cosinal distance between the vectors i.e the angles between the vectors
# dist is inversely proportional to similarity
# there is a function available in sci-kit learn which is cosine similarity

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
similarity = cosine_similarity(vectors)

In [67]:
sorted(similarity[0],reverse=True)[1:11]
# sorting from similarity of a movie in descending order such that we get first 10 similar movies other than the original one
# but here comes the problem that is we lsoe the index no of the movies when we sort
# to solve it we use enumerate

[0.2953020527757655,
 0.2755193843889919,
 0.26222244603662925,
 0.260132990857236,
 0.24779731389167606,
 0.24779731389167606,
 0.24745669886621618,
 0.24455799402225925,
 0.2421000623531261,
 0.24182541670333726]

In [68]:
list(enumerate(similarity[0]))

[(0, 1.0000000000000002),
 (1, 0.08471737420873576),
 (2, 0.08740748201220976),
 (3, 0.0695678476053965),
 (4, 0.19346033336266982),
 (5, 0.10060545457319173),
 (6, 0.03364315551262445),
 (7, 0.14673479641335554),
 (8, 0.06243905410544627),
 (9, 0.09086217008485092),
 (10, 0.101338918387628),
 (11, 0.09464970485606021),
 (12, 0.09037128496931669),
 (13, 0.04499212706658476),
 (14, 0.12988108336653278),
 (15, 0.06282808624375433),
 (16, 0.07894736842105264),
 (17, 0.13977653617040256),
 (18, 0.09626070358206487),
 (19, 0.08175191193132876),
 (20, 0.08439828691971296),
 (21, 0.11128297681493143),
 (22, 0.06362847629757779),
 (23, 0.09197090092274487),
 (24, 0.05564148840746572),
 (25, 0.051298917604257706),
 (26, 0.152008377581442),
 (27, 0.18541926977182407),
 (28, 0.116543309349613),
 (29, 0.06335829046432676),
 (30, 0.08594700851870801),
 (31, 0.1411956236812263),
 (32, 0.08671099695241201),
 (33, 0.08885233166386385),
 (34, 0.0),
 (35, 0.10147651372376076),
 (36, 0.1692777916923361),
 (37, 0.07509392614826384),
 (38, 0.07647191129018727),
 (39, 0.08000711205939975),
 (40, 0.061313933948496574),
 (41, 0.1692777916923361),
 (42, 0.0),
 (43, 0.09176629354822471),
 (44, 0.03382550457458692),
 (45, 0.08111071056538127),
 (46, 0.126673647984535),
 (47, 0.1873171623163388),
 (48, 0.0830812984794528),
 (49, 0.0602475233128778),
 (50, 0.116543309349613),
 (51, 0.09304036594559835),
 (52, 0.14843120879858804),
 (53, 0.04188539082916955),
 (54, 0.02249606353329238),
 (55, 0.06158950357943867),
 (56, 0.16222142113076254),
 (57, 0.019389168358237032),
 (58, 0.06622661785325219),
 (59, 0.08903057122447033),
 (60, 0.01860807318911967),
 (61, 0.24779731389167606),
 (62, 0.0837707816583391),
 (63, 0.08048436365855338),
 (64, 0.028676966733820218),
 (65, 0.018486846666163393),
 (66, 0.01813690625275029),
 (67, 0.1453922723390424),
 (68, 0.13334518676566626),
 (69, 0.02649064714130088),
 (70, 0.12515654358043973),
 (71, 0.061313933948496574),
 (72, 0.1391037210186643),
 (73, 0.0331133089266261),
 (74, 0.2024645717996314),
 (75, 0.14843120879858804),
 (76, 0.06952346619889824),
 (77, 0.012706162331256701),
 (78, 0.043747863925980714),
 (79, 0.08175191193132876),
 (80, 0.049930699897395465),
 (81, 0.11092107999698035),
 (82, 0.07175473098524099),
 (83, 0.17996850826633903),
 (84, 0.12072654548783007),
 (85, 0.1141270638770543),
 (86, 0.05619514869490164),
 (87, 0.11295649894498103),
 (88, 0.06562179588897107),
 (89, 0.05178671543366414),
 (90, 0.043355498476206004),
 (91, 0.17206180040292132),
 (92, 0.06282808624375433),
 (93, 0.07254762501100118),
 (94, 0.1433848336691011),
 (95, 0.16742770563222897),
 (96, 0.08000711205939975),
 (97, 0.06882472016116853),
 (98, 0.07336739820667779),
 (99, 0.023662426214015053),
 (100, 0.07079923254047887),
 (101, 0.07509392614826384),
 (102, 0.12565617248750863),
 (103, 0.07987230638308718),
 (104, 0.057353933467640436),
 (105, 0.10619884881071831),
 (106, 0.050464733268936676),
 (107, 0.06282808624375433),
 (108, 0.14509525002200235),
 (109, 0.06488856845230502),
 (110, 0.04456565178215865),
 (111, 0.152008377581442),
 (112, 0.07792865001991967),
 (113, 0.04456565178215865),
 (114, 0.047324852428030105),
 (115, 0.04499212706658476),
 (116, 0.047324852428030105),
 (117, 0.0602475233128778),
 (118, 0.02986738455447495),
 (119, 0.042973504259354006),
 (120, 0.0),
 (121, 0.11128297681493143),
 (122, 0.11470786693528087),
 (123, 0.11037769642208699),
 (124, 0.053418342734682205),
 (125, 0.07443229275647868),
 (126, 0.12091270835166862),
 (127, 0.14789477332930714),
 (128, 0.0),
 (129, 0.08594700851870801),
 (130, 0.03993615319154359),
 (131, 0.08240856434303293),
 (132, 0.039344473768231684),
 (133, 0.0582716546748065),
 (134, 0.13530201829834768),
 (135, 0.0),
 (136, 0.02249606353329238),
 (137, 0.02640278405633409),
 (138, 0.12824729401064427),
 (139, 0.12166606584807191),
 (140, 0.04188539082916955),
 (141, 0.10060545457319173),
 (142, 0.08226127456606226),
 (143, 0.08671099695241201),
 (144, 0.0415406492397264),
 (145, 0.019389168358237032),
 (146, 0.013961796943056517),
 (147, 0.057353933467640436),
 (148, 0.09197090092274487),
 (149, 0.15737789507292674),
 (150, 0.16426202236672155),
 (151, 0.2029530274475215),
 (152, 0.061313933948496574),
 (153, 0.08048436365855338),
 (154, 0.043747863925980714),
 (155, 0.020942695414584774),
 (156, 0.060363272743915036),
 (157, 0.0936585811581694),
 (158, 0.12262786789699313),
 (159, 0.0602475233128778),
 (160, 0.10498162982203109),
 (161, 0.03181423814878889),
 (162, 0.05647824947249051),
 (163, 0.07509392614826384),
 (164, 0.08346223261119858),
 (165, 0.046829290579084706),
 (166, 0.11959121830873498),
 (167, 0.09544271444636668),
 (168, 0.1873171623163388),
 (169, 0.10559715077387793),
 (170, 0.1267165809286535),
 (171, 0.04543108504242546),
 (172, 0.20295302744752153),
 (173, 0.019117977822546817),
 (174, 0.10259783520851541),
 (175, 0.06748819059987714),
 (176, 0.029617443887954616),
 (177, 0.0),
 (178, 0.019672236884115842),
 (179, 0.06684847767323797),
 (180, 0.02249606353329238),
 (181, 0.03604920469572501),
 (182, 0.13245323570650439),
 (183, 0.07122445697957627),
 (184, 0.13872950617564817),
 (185, 0.050669459193814),
 (186, 0.05901671065234752),
 (187, 0.12072654548783007),
 (188, 0.02271554252121273),
 (189, 0.1147078669352809),
 (190, 0.07079923254047887),
 (191, 0.050669459193814),
 (192, 0.04783648732349399),
 (193, 0.07878168645790681),
 (194, 0.0),
 (195, 0.0602475233128778),
 (196, 0.040555355282690636),
 (197, 0.037463432463267755),
 (198, 0.0582716546748065),
 (199, 0.08594700851870801),
 (200, 0.1147078669352809),
 (201, 0.0),
 (202, 0.02060214108575823),
 (203, 0.0978231976089037),
 (204, 0.046348977465932154),
 (205, 0.1147078669352809),
 (206, 0.0870571500132014),
 (207, 0.07694837640638656),
 (208, 0.12487810821089254),
 (209, 0.10619884881071831),
 (210, 0.10559715077387793),
 (211, 0.024455799402225926),
 (212, 0.06748819059987714),
 (213, 0.05945550264670635),
 (214, 0.0),
 (215, 0.065033247714309),
 (216, 0.06131393394849658),
 (217, 0.08594700851870801),
 (218, 0.040555355282690636),
 (219, 0.09733285267845754),
 (220, 0.2073221072156823),
 (221, 0.046829290579084706),
 (222, 0.07868894753646337),
 (223, 0.10259783520851541),
 (224, 0.05775642214923893),
 (225, 0.04783648732349399),
 (226, 0.029617443887954616),
 (227, 0.08346223261119858),
 (228, 0.1124803176664619),
 (229, 0.1095080149111477),
 (230, 0.09365858115816939),
 (231, 0.0),
 (232, 0.106676149412533),
 (233, 0.11164843913471803),
 (234, 0.07254762501100116),
 (235, 0.07421560439929402),
 (236, 0.116543309349613),
 (237, 0.06131393394849658),
 (238, 0.11020775375559676),
 (239, 0.12105003117656307),
 (240, 0.046829290579084706),
 (241, 0.07792865001991967),
 (242, 0.08000711205939975),
 (243, 0.09176629354822471),
 (244, 0.09544271444636668),
 (245, 0.08111071056538127),
 (246, 0.09558988911273408),
 (247, 0.0),
 (248, 0.04499212706658476),
 (249, 0.12725695259515557),
 (250, 0.0),
 (251, 0.046829290579084706),
 (252, 0.018367958959266125),
 (253, 0.06335829046432676),
 (254, 0.06882472016116853),
 (255, 0.0),
 (256, 0.09544271444636668),
 (257, 0.052631578947368425),
 (258, 0.017595383576944672),
 (259, 0.06131393394849658),
 (260, 0.2073221072156823),
 (261, 0.024455799402225926),
 (262, 0.10838874619051501),
 (263, 0.09733285267845754),
 (264, 0.0),
 (265, 0.02782074420373286),
 (266, 0.12369267399882337),
 (267, 0.06917144638660747),
 (268, 0.05006261743217589),
 (269, 0.042973504259354006),
 (270, 0.09086217008485092),
 (271, 0.09269795493186431),
 (272, 0.028239124736245257),
 (273, 0.019968076595771794),
 (274, 0.08894313631879691),
 (275, 0.1777046633277277),
 (276, 0.0662266178532522),
 (277, 0.052786150730834015),
 (278, 0.12091270835166862),
 (279, 0.09365858115816941),
 (280, 0.0),
 (281, 0.065033247714309),
 (282, 0.04456565178215865),
 (283, 0.028239124736245257),
 (284, 0.018731716231633878),
 (285, 0.019968076595771794),
 (286, 0.0792740035289418),
 (287, 0.05195243334661311),
 (288, 0.021119430154775586),
 (289, 0.03797316245786213),
 (290, 0.06131393394849658),
 (291, 0.05006261743217589),
 (292, 0.09037128496931669),
 (293, 0.02271554252121273),
 (294, 0.11037769642208699),
 (295, 0.10814761408717502),
 (296, 0.03850428143282595),
 (297, 0.04499212706658476),
 (298, 0.0),
 (299, 0.07165743639000186),
 (300, 0.16563698349810538),
 (301, 0.11092107999698035),
 (302, 0.05695974368679319),
 (303, 0.027036903521793755),
 (304, 0.0662266178532522),
 (305, 0.1612292318775042),
 (306, 0.12988108336653278),
 (307, 0.10926834468453098),
 (308, 0.06765100914917384),
 (309, 0.0582716546748065),
 (310, 0.0309344112444873),
 (311, 0.15018785229652765),
 (312, 0.10259783520851541),
 (313, 0.04188539082916955),
 (314, 0.0),
 (315, 0.08471737420873576),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.10619884881071831),
 (320, 0.0602475233128778),
 (321, 0.0),
 (322, 0.213352298825066),
 (323, 0.02913582733740325),
 (324, 0.019529164171612674),
 (325, 0.06335829046432676),
 (326, 0.05195243334661311),
 (327, 0.028239124736245257),
 (328, 0.0207703246198632),
 (329, 0.08226127456606226),
 (330, 0.10390486669322622),
 (331, 0.09176629354822471),
 (332, 0.106676149412533),
 (333, 0.05006261743217589),
 (334, 0.14673479641335554),
 (335, 0.046348977465932154),
 (336, 0.07079923254047887),
 (337, 0.04543108504242546),
 (338, 0.0),
 (339, 0.0396370017644709),
 (340, 0.04891159880445185),
 (341, 0.07509392614826384),
 (342, 0.17914359097500465),
 (343, 0.016303866268150616),
 (344, 0.029617443887954616),
 (345, 0.02271554252121273),
 (346, 0.02742042485535409),
 (347, 0.0),
 (348, 0.0415406492397264),
 (349, 0.08111071056538127),
 (350, 0.05006261743217589),
 (351, 0.0),
 (352, 0.025031308716087945),
 (353, 0.042973504259354006),
 (354, 0.022075539284417398),
 (355, 0.037463432463267755),
 (356, 0.12487810821089254),
 (357, 0.0),
 (358, 0.04499212706658476),
 (359, 0.024455799402225926),
 (360, 0.04223886030955117),
 (361, 0.076004188790721),
 (362, 0.09933992677987831),
 (363, 0.09493290614465533),
 (364, 0.023414645289542353),
 (365, 0.07694837640638656),
 (366, 0.05564148840746572),
 (367, 0.0),
 (368, 0.12725695259515557),
 (369, 0.11959121830873498),
 (370, 0.052631578947368425),
 (371, 0.11959121830873498),
 (372, 0.04836508334066745),
 (373, 0.1813690625275029),
 (374, 0.028132762306570986),
 (375, 0.0623109738595896),
 (376, 0.06882472016116853),
 (377, 0.0),
 (378, 0.0),
 (379, 0.04704761013358541),
 (380, 0.05407380704358751),
 (381, 0.0837707816583391),
 (382, 0.0),
 (383, 0.10218988991416096),
 (384, 0.029617443887954616),
 (385, 0.0),
 (386, 0.022075539284417398),
 (387, 0.024455799402225926),
 (388, 0.0),
 (389, 0.08603090020146066),
 (390, 0.019389168358237032),
 (391, 0.05695974368679319),
 (392, 0.03181423814878889),
 (393, 0.0),
 (394, 0.025334729596907),
 (395, 0.05195243334661311),
 (396, 0.04456565178215865),
 (397, 0.05407380704358751),
 (398, 0.0),
 (399, 0.018857857160117855),
 (400, 0.09037128496931669),
 (401, 0.031219527052723135),
 (402, 0.07792865001991967),
 (403, 0.0830812984794528),
 (404, 0.06243905410544627),
 (405, 0.05564148840746572),
 (406, 0.015756337291581362),
 (407, 0.021873931962990357),
 (408, 0.03382550457458692),
 (409, 0.0),
 (410, 0.09269795493186431),
 (411, 0.05195243334661311),
 (412, 0.1661625969589056),
 (413, 0.12988108336653278),
 (414, 0.031219527052723135),
 (415, 0.04772135722318334),
 (416, 0.05195243334661311),
 (417, 0.025334729596907),
 (418, 0.024455799402225926),
 (419, 0.06952346619889824),
 (420, 0.11357771260606365),
 (421, 0.023918243661746996),
 (422, 0.11846977555181847),
 (423, 0.0415406492397264),
 (424, 0.03850428143282595),
 (425, 0.065033247714309),
 (426, 0.054410718758250876),
 (427, 0.02666903735313325),
 (428, 0.050464733268936676),
 (429, 0.0),
 (430, 0.07543142864047142),
 (431, 0.019672236884115842),
 (432, 0.11470786693528089),
 (433, 0.0331133089266261),
 (434, 0.0),
 (435, 0.0331133089266261),
 (436, 0.0),
 (437, 0.02666903735313325),
 (438, 0.16563698349810535),
 (439, 0.0533380747062665),
 (440, 0.02294157338705618),
 (441, 0.04588314677411236),
 (442, 0.046829290579084706),
 (443, 0.06390214842634574),
 (444, 0.0),
 (445, 0.101338918387628),
 (446, 0.023414645289542353),
 (447, 0.06622661785325219),
 (448, 0.021873931962990357),
 (449, 0.11295649894498103),
 (450, 0.04188539082916955),
 (451, 0.07509392614826384),
 (452, 0.028239124736245257),
 (453, 0.024455799402225926),
 (454, 0.11959121830873498),
 (455, 0.08111071056538127),
 (456, 0.04223886030955117),
 (457, 0.08885233166386385),
 (458, 0.03458572319330373),
 (459, 0.023414645289542353),
 (460, 0.023174488732966077),
 (461, 0.20025046972870353),
 (462, 0.031365073422390276),
 (463, 0.026315789473684213),
 (464, 0.0),
 (465, 0.0),
 (466, 0.14159846508095775),
 (467, 0.10385162309931599),
 (468, 0.028676966733820218),
 (469, 0.05695974368679319),
 (470, 0.04543108504242546),
 (471, 0.06390214842634574),
 (472, 0.106676149412533),
 (473, 0.09464970485606021),
 (474, 0.0),
 (475, 0.042973504259354006),
 (476, 0.17292861596651865),
 (477, 0.0),
 (478, 0.05475400745557385),
 (479, 0.07733602811121826),
 (480, 0.0978231976089037),
 (481, 0.0),
 (482, 0.022282825891079324),
 (483, 0.1324532357065044),
 (484, 0.031219527052723135),
 (485, 0.04783648732349399),
 (486, 0.08031157077540445),
 (487, 0.16222142113076254),
 (488, 0.05998950275544634),
 (489, 0.0),
 (490, 0.1691275228729346),
 (491, 0.09304036594559835),
 (492, 0.05816750507471109),
 (493, 0.046192127684579004),
 (494, 0.0),
 (495, 0.18074256993863339),
 (496, 0.0),
 (497, 0.0),
 (498, 0.06917144638660747),
 (499, 0.0),
 (500, 0.025334729596907),
 (501, 0.06839855680567694),
 (502, 0.16222142113076254),
 (503, 0.07336739820667777),
 (504, 0.0),
 (505, 0.1691275228729346),
 (506, 0.047324852428030105),
 (507, 0.260132990857236),
 (508, 0.14673479641335554),
 (509, 0.022075539284417398),
 (510, 0.0989541391990587),
 (511, 0.09037128496931669),
 (512, 0.02782074420373286),
 (513, 0.177343107178349),
 (514, 0.036973693332326786),
 (515, 0.025334729596907),
 (516, 0.027036903521793755),
 (517, 0.0),
 (518, 0.043355498476206004),
 (519, 0.0),
 (520, 0.0),
 (521, 0.024455799402225926),
 (522, 0.02294157338705618),
 (523, 0.04947706959952935),
 (524, 0.0),
 (525, 0.03650267163704923),
 (526, 0.028239124736245257),
 (527, 0.03458572319330373),
 (528, 0.022075539284417398),
 (529, 0.18731716231633883),
 (530, 0.052631578947368425),
 (531, 0.04588314677411236),
 (532, 0.021300716142115247),
 (533, 0.044151078568834795),
 (534, 0.09365858115816941),
 (535, 0.10012523486435178),
 (536, 0.11707322644771176),
 (537, 0.0582716546748065),
 (538, 0.0),
 (539, 0.26222244603662925),
 (540, 0.07336739820667779),
 (541, 0.10138838820672659),
 (542, 0.03478392380269825),
 (543, 0.09464970485606021),
 (544, 0.05407380704358751),
 (545, 0.025976216673306556),
 (546, 0.046348977465932154),
 (547, 0.08000711205939975),
 (548, 0.0),
 (549, 0.18693292157876878),
 (550, 0.018367958959266125),
 (551, 0.03650267163704923),
 (552, 0.0),
 (553, 0.03065696697424829),
 (554, 0.0),
 (555, 0.10076376380498041),
 (556, 0.028239124736245257),
 (557, 0.12515654358043973),
 (558, 0.020942695414584774),
 (559, 0.03065696697424829),
 (560, 0.03604920469572501),
 (561, 0.03244428422615251),
 (562, 0.03181423814878889),
 (563, 0.09365858115816941),
 (564, 0.09037128496931669),
 (565, 0.03244428422615251),
 (566, 0.019529164171612674),
 (567, 0.025031308716087945),
 (568, 0.14808721943977307),
 (569, 0.034010851192571794),
 (570, 0.06765100914917384),
 (571, 0.04188539082916955),
 (572, 0.10559715077387793),
 (573, 0.0207703246198632),
 (574, 0.022075539284417398),
 (575, 0.06882472016116853),
 (576, 0.050669459193814),
 (577, 0.1976738731537168),
 (578, 0.03419927840283847),
 (579, 0.15789473684210528),
 (580, 0.024738534799764674),
 (581, 0.1391037210186643),
 (582, 0.24745669886621618),
 (583, 0.03771571432023571),
 (584, 0.08111071056538127),
 (585, 0.023662426214015053),
 (586, 0.046829290579084706),
 (587, 0.09269795493186431),
 (588, 0.02666903735313325),
 (589, 0.11239029738980326),
 (590, 0.031219527052723135),
 (591, 0.0623109738595896),
 (592, 0.021486752129677003),
 (593, 0.0),
 (594, 0.05006261743217589),
 (595, 0.18731716231633883),
 (596, 0.09365858115816941),
 (597, 0.08740748201220976),
 (598, 0.03627381250550058),
 (599, 0.071367910210471),
 (600, 0.06390214842634574),
 (601, 0.03294217956952912),
 (602, 0.09176629354822471),
 (603, 0.051298917604257706),
 (604, 0.052631578947368425),
 (605, 0.019672236884115842),
 (606, 0.0),
 (607, 0.07755667343294813),
 (608, 0.0301237616564389),
 (609, 0.04783648732349399),
 (610, 0.058038100008800934),
 (611, 0.02271554252121273),
 (612, 0.060363272743915036),
 (613, 0.03539961627023944),
 (614, 0.05775642214923893),
 (615, 0.06243905410544627),
 (616, 0.02913582733740325),
 (617, 0.051298917604257706),
 (618, 0.08520286456846099),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06917144638660747),
 (622, 0.021300716142115247),
 (623, 0.0),
 (624, 0.10147651372376076),
 (625, 0.03181423814878889),
 (626, 0.08346223261119858),
 (627, 0.11164843913471803),
 (628, 0.0),
 (629, 0.04783648732349399),
 (630, 0.025031308716087945),
 (631, 0.03797316245786213),
 (632, 0.12515654358043973),
 (633, 0.02271554252121273),
 (634, 0.076004188790721),
 (635, 0.06882472016116853),
 (636, 0.023174488732966077),
 (637, 0.025031308716087945),
 (638, 0.03458572319330373),
 (639, 0.023918243661746996),
 (640, 0.061806423257274694),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10259783520851541),
 (644, 0.05006261743217589),
 (645, 0.04120428217151646),
 (646, 0.052631578947368425),
 (647, 0.04947706959952935),
 (648, 0.03181423814878889),
 (649, 0.0),
 (650, 0.101338918387628),
 (651, 0.0),
 (652, 0.03582871819500093),
 (653, 0.1147078669352809),
 (654, 0.09984038297885897),
 (655, 0.023174488732966077),
 (656, 0.0),
 (657, 0.03364315551262445),
 (658, 0.04891159880445185),
 (659, 0.025334729596907),
 (660, 0.09933992677987831),
 (661, 0.1518926498314485),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06131393394849658),
 (665, 0.06684847767323797),
 (666, 0.07254762501100118),
 (667, 0.0),
 (668, 0.13530201829834768),
 (669, 0.03627381250550058),
 (670, 0.01769980813511972),
 (671, 0.06952346619889824),
 (672, 0.027036903521793755),
 (673, 0.05816750507471109),
 (674, 0.09428928580058928),
 (675, 0.10471347707292386),
 (676, 0.028239124736245257),
 (677, 0.04836508334066745),
 (678, 0.12262786789699316),
 (679, 0.0),
 (680, 0.06882472016116853),
 (681, 0.028239124736245257),
 (682, 0.02043797798283219),
 (683, 0.04836508334066745),
 (684, 0.0),
 (685, 0.0331133089266261),
 (686, 0.026315789473684213),
 (687, 0.10526315789473685),
 (688, 0.042973504259354006),
 (689, 0.0),
 (690, 0.025334729596907),
 (691, 0.06131393394849658),
 (692, 0.09125667909262308),
 (693, 0.03539961627023944),
 (694, 0.022075539284417398),
 (695, 0.06765100914917384),
 (696, 0.039344473768231684),
 (697, 0.0),
 (698, 0.04456565178215865),
 (699, 0.03721614637823934),
 (700, 0.02782074420373286),
 (701, 0.05407380704358751),
 (702, 0.02294157338705618),
 (703, 0.0207703246198632),
 (704, 0.055824219567359015),
 (705, 0.023662426214015053),
 (706, 0.044151078568834795),
 (707, 0.0),
 (708, 0.024182541670333724),
 (709, 0.019672236884115842),
 (710, 0.05775642214923893),
 (711, 0.052631578947368425),
 (712, 0.024182541670333724),
 (713, 0.02666903735313325),
 (714, 0.0),
 (715, 0.09933992677987831),
 (716, 0.02782074420373286),
 (717, 0.0),
 (718, 0.08520286456846099),
 (719, 0.0),
 (720, 0.07792865001991967),
 (721, 0.0331133089266261),
 (722, 0.0),
 (723, 0.024182541670333724),
 (724, 0.023662426214015053),
 (725, 0.028676966733820218),
 (726, 0.0),
 (727, 0.0309344112444873),
 (728, 0.07098727864204515),
 (729, 0.05006261743217589),
 (730, 0.02742042485535409),
 (731, 0.0533380747062665),
 (732, 0.06622661785325219),
 (733, 0.06282808624375433),
 (734, 0.05619514869490164),
 (735, 0.06814662756363819),
 (736, 0.02913582733740325),

In [69]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x:x[1])
# sorting enumerated list with respect to column 1 not column 0

[(0, 1.0000000000000002),
 (1916, 0.2953020527757655),
 (1214, 0.2755193843889919),
 (539, 0.26222244603662925),
 (507, 0.260132990857236),
 (61, 0.24779731389167606),
 (3728, 0.24779731389167606),
 (582, 0.24745669886621618),
 (1202, 0.24455799402225925),
 (1192, 0.2421000623531261),
 (2405, 0.24182541670333726),
 (778, 0.23662426214015048),
 (3671, 0.23174488732966075),
 (1319, 0.22710998958306758),
 (4044, 0.22184215999396073),
 (3606, 0.21964884255348974),
 (322, 0.213352298825066),
 (220, 0.2073221072156823),
 (260, 0.2073221072156823),
 (2782, 0.20395079136182276),
 (172, 0.20295302744752153),
 (151, 0.2029530274475215),
 (1440, 0.20277677641345318),
 (3325, 0.20277677641345318),
 (74, 0.2024645717996314),
 (1087, 0.2020475485519274),
 (461, 0.20025046972870353),
 (2968, 0.20025046972870353),
 (577, 0.1976738731537168),
 (2329, 0.19509974314292702),
 (931, 0.19474520942613005),
 (972, 0.19474520942613005),
 (4185, 0.19466570535691505),
 (4, 0.19346033336266982),
 (973, 0.19194297398747862),
 (529, 0.18731716231633883),
 (595, 0.18731716231633883),
 (4396, 0.18731716231633883),
 (47, 0.1873171623163388),
 (168, 0.1873171623163388),
 (3632, 0.1873171623163388),
 (549, 0.18693292157876878),
 (1069, 0.18668326147193276),
 (27, 0.18541926977182407),
 (1273, 0.18394180184548975),
 (1533, 0.18353258709644943),
 (2969, 0.18136906252750296),
 (373, 0.1813690625275029),
 (2997, 0.1813690625275029),
 (495, 0.18074256993863339),
 (3995, 0.18074256993863339),
 (83, 0.17996850826633903),
 (4014, 0.17954621161490197),
 (342, 0.17914359097500465),
 (275, 0.1777046633277277),
 (513, 0.177343107178349),
 (1346, 0.17699808135119718),
 (1379, 0.17521916101261562),
 (4329, 0.17521916101261562),
 (2200, 0.17316974359835272),
 (476, 0.17292861596651865),
 (91, 0.17206180040292132),
 (36, 0.1692777916923361),
 (41, 0.1692777916923361),
 (490, 0.1691275228729346),
 (505, 0.1691275228729346),
 (95, 0.16742770563222897),
 (412, 0.1661625969589056),
 (3091, 0.1661625969589056),
 (300, 0.16563698349810538),
 (438, 0.16563698349810535),
 (4074, 0.16452254913212452),
 (150, 0.16426202236672155),
 (56, 0.16222142113076254),
 (487, 0.16222142113076254),
 (502, 0.16222142113076254),
 (2756, 0.16222142113076254),
 (1176, 0.16222142113076252),
 (1327, 0.16222142113076252),
 (305, 0.1612292318775042),
 (2511, 0.15907119074394446),
 (579, 0.15789473684210528),
 (3536, 0.15747244473304667),
 (149, 0.15737789507292674),
 (1874, 0.15737789507292674),
 (4006, 0.15737789507292674),
 (1961, 0.1540171257313038),
 (1029, 0.15389675281277312),
 (2727, 0.15328483487124145),
 (26, 0.152008377581442),
 (111, 0.152008377581442),
 (661, 0.1518926498314485),
 (1342, 0.15018785229652767),
 (311, 0.15018785229652765),
 (52, 0.14843120879858804),
 (75, 0.14843120879858804),
 (1353, 0.14843120879858804),
 (568, 0.14808721943977307),
 (127, 0.14789477332930714),
 (7, 0.14673479641335554),
 (334, 0.14673479641335554),
 (508, 0.14673479641335554),
 (1978, 0.14673479641335554),
 (1392, 0.14659886790209342),
 (1475, 0.14659886790209342),
 (1369, 0.14567913668701626),
 (67, 0.1453922723390424),
 (3160, 0.1453922723390424),
 (108, 0.14509525002200235),
 (3429, 0.144560827395728),
 (94, 0.1433848336691011),
 (920, 0.1433848336691011),
 (2071, 0.1433848336691011),
 (1295, 0.1419745572840903),
 (466, 0.14159846508095775),
 (31, 0.1411956236812263),
 (17, 0.13977653617040256),
 (72, 0.1391037210186643),
 (581, 0.1391037210186643),
 (3407, 0.1391037210186643),
 (1934, 0.13904693239779645),
 (184, 0.13872950617564817),
 (935, 0.13834289277321493),
 (1325, 0.13834289277321493),
 (2165, 0.13710212427677043),
 (1199, 0.13629325512727639),
 (942, 0.13572417850765922),
 (134, 0.13530201829834768),
 (668, 0.13530201829834768),
 (3952, 0.13530201829834768),
 (3979, 0.13530201829834768),
 (859, 0.13518451760896877),
 (1013, 0.13518451760896877),
 (1107, 0.13497638119975428),
 (4526, 0.13497638119975428),
 (1493, 0.13476498501489081),
 (777, 0.13369695534647594),
 (1007, 0.13369695534647594),
 (68, 0.13334518676566626),
 (1556, 0.13334518676566626),
 (2492, 0.13334518676566626),
 (483, 0.1324532357065044),
 (1484, 0.1324532357065044),
 (182, 0.13245323570650439),
 (2129, 0.13245323570650439),
 (843, 0.13157894736842107),
 (2177, 0.13157894736842107),
 (3352, 0.13157894736842107),
 (4336, 0.13124359177794215),
 (2476, 0.130066495428618),
 (14, 0.12988108336653278),
 (306, 0.12988108336653278),
 (413, 0.12988108336653278),
 (1084, 0.12988108336653278),
 (3864, 0.12988108336653278),
 (773, 0.12977713690461004),
 (1156, 0.12977713690461004),
 (2056, 0.12977713690461004),
 (2374, 0.12977713690461004),
 (3779, 0.12977713690461004),
 (2869, 0.12892051277806202),
 (138, 0.12824729401064427),
 (249, 0.12725695259515557),
 (368, 0.12725695259515557),
 (1470, 0.12725695259515557),
 (2319, 0.12725695259515557),
 (4421, 0.12725695259515557),
 (838, 0.12695834376925202),
 (170, 0.1267165809286535),
 (46, 0.126673647984535),
 (1892, 0.12565617248750865),
 (3081, 0.12565617248750865),
 (4341, 0.12565617248750865),
 (102, 0.12565617248750863),
 (70, 0.12515654358043973),
 (557, 0.12515654358043973),
 (632, 0.12515654358043973),
 (3620, 0.12515654358043973),
 (3626, 0.12515654358043973),
 (208, 0.12487810821089254),
 (356, 0.12487810821089254),
 (1094, 0.12487810821089254),
 (1272, 0.12487810821089254),
 (1654, 0.12487810821089254),
 (2580, 0.12487810821089254),
 (1271, 0.1246219477191792),
 (1827, 0.12389865694583803),
 (266, 0.12369267399882337),
 (2446, 0.12369267399882337),
 (4223, 0.12369267399882337),
 (1320, 0.12316768503861272),
 (678, 0.12262786789699316),
 (781, 0.12262786789699316),
 (1045, 0.12262786789699316),
 (1752, 0.12262786789699316),
 (1770, 0.12262786789699316),
 (158, 0.12262786789699313),
 (2280, 0.12227899701112963),
 (139, 0.12166606584807191),
 (850, 0.12166606584807191),
 (1000, 0.12166606584807191),
 (239, 0.12105003117656307),
 (126, 0.12091270835166862),
 (278, 0.12091270835166862),
 (1054, 0.12091270835166862),
 (84, 0.12072654548783007),
 (187, 0.12072654548783007),
 (2131, 0.12072654548783007),
 (2648, 0.1204950466257556),
 (3374, 0.1204950466257556),
 (4395, 0.1204950466257556),
 (4650, 0.1204950466257556),
 (166, 0.11959121830873498),
 (369, 0.11959121830873498),
 (371, 0.11959121830873498),
 (454, 0.11959121830873498),
 (900, 0.11959121830873498),
 (2484, 0.11959121830873498),
 (3233, 0.11959121830873498),
 (1737, 0.11891100529341271),
 (422, 0.11846977555181847),
 (1299, 0.11846977555181847),
 (2737, 0.11846977555181847),
 (814, 0.11831213107007527),
 (808, 0.11803342130469505),
 (1669, 0.11803342130469505),
 (536, 0.11707322644771176),
 (1613, 0.11707322644771176),
 (4127, 0.11707322644771176),
 (28, 0.116543309349613),
 (50, 0.116543309349613),
 (236, 0.116543309349613),
 (1297, 0.11587244366483038),
 (1804, 0.11587244366483038),
 (2543, 0.11587244366483038),
 (3210, 0.11506355109724453),
 (189, 0.1147078669352809),
 (200, 0.1147078669352809),
 (205, 0.1147078669352809),
 (653, 0.1147078669352809),
 (1137, 0.1147078669352809),
 (1414, 0.1147078669352809),
 (1571, 0.1147078669352809),
 (2327, 0.1147078669352809),
 (2670, 0.1147078669352809),
 (2785, 0.1147078669352809),
 (4504, 0.1147078669352809),
 (4568, 0.1147078669352809),
 (432, 0.11470786693528089),
 (122, 0.11470786693528087),
 (1002, 0.11470786693528087),
 (1829, 0.11470786693528087),
 (85, 0.1141270638770543),
 (4258, 0.11357771260606367),
 (420, 0.11357771260606365),
 (1508, 0.11357771260606365),
 (2816, 0.11357771260606365),
 (1359, 0.11314714296070713),
 (87, 0.11295649894498103),
 (449, 0.11295649894498103),
 (775, 0.11295649894498103),
 (1612, 0.11295649894498103),
 (228, 0.1124803176664619),
 (870, 0.1124803176664619),
 (1231, 0.1124803176664619),
 (3836, 0.1124803176664619),
 (4219, 0.11243619908556624),
 (3145, 0.11239029738980327),
 (589, 0.11239029738980326),
 (233, 0.11164843913471803),
 (627, 0.11164843913471803),
 (1406, 0.11164843913471803),
 (2157, 0.11164843913471803),
 (2368, 0.11141412945539662),
 (3307, 0.11141412945539662),
 (889, 0.11134983352076112),
 (21, 0.11128297681493143),
 (121, 0.11128297681493143),
 (81, 0.11092107999698035),
 (301, 0.11092107999698035),
 (123, 0.11037769642208699),
 (294, 0.11037769642208699),
 (937, 0.11037769642208699),
 (238, 0.11020775375559676),
 (3426, 0.10968169942141637),
 (1235, 0.10968169942141635),
 (1585, 0.10968169942141635),
 (1696, 0.10968169942141635),
 (2068, 0.10968169942141635),
 (2144, 0.10968169942141635),
 (3006, 0.10968169942141635),
 (229, 0.1095080149111477),
 (1016, 0.10936965981495178),
 (1218, 0.10936965981495178),
 (3551, 0.10936965981495178),
 (307, 0.10926834468453098),
 (1031, 0.10882143751650175),
 (1497, 0.10882143751650175),
 (1766, 0.10882143751650175),
 (262, 0.10838874619051501),
 (295, 0.10814761408717502),
 (1941, 0.10814761408717502),
 (3496, 0.10814761408717502),
 (4457, 0.10814761408717502),
 (939, 0.1074861545850028),
 (1173, 0.10743376064838502),
 (1570, 0.1068366854693644),
 (232, 0.106676149412533),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (786, 0.106676149412533),
 (1035, 0.106676149412533),
 (1767, 0.106676149412533),
 (752, 0.10650358071057624),
 (1492, 0.10650358071057624),
 (105, 0.10619884881071831),
 (209, 0.10619884881071831),
 (319, 0.10619884881071831),
 (1278, 0.10619884881071831),
 (2517, 0.10619884881071831),
 (169, 0.10559715077387793),
 (210, 0.10559715077387793),
 (572, 0.10559715077387793),
 (3628, 0.10559715077387793),
 (3903, 0.10557230146166804),
 (687, 0.10526315789473685),
 (2813, 0.10526315789473685),
 (3338, 0.10526315789473685),
 (160, 0.10498162982203109),
 (675, 0.10471347707292386),
 (1451, 0.10471347707292386),
 (330, 0.10390486669322622),
 (467, 0.10385162309931599),
 (800, 0.1037571695799112),
 (1520, 0.1037571695799112),
 (2452, 0.1037571695799112),
 (2630, 0.1037571695799112),
 (3719, 0.1037571695799112),
 (3837, 0.1037571695799112),
 (740, 0.10301070542879115),
 (2102, 0.10301070542879115),
 (174, 0.10259783520851541),
 (223, 0.10259783520851541),
 (312, 0.10259783520851541),
 (643, 0.10259783520851541),
 (986, 0.10259783520851541),
 (1080, 0.10259783520851541),
 (1193, 0.10259783520851541),
 (1292, 0.10259783520851541),
 (2087, 0.10259783520851541),
 (4288, 0.10259783520851541),
 (383, 0.10218988991416096),
 (1401, 0.10218988991416095),
 (1435, 0.10218988991416095),
 (35, 0.10147651372376076),
 (624, 0.10147651372376076),
 (1741, 0.10147651372376076),
 (2758, 0.10147651372376076),
 (3053, 0.10147651372376076),
 (3889, 0.10147651372376076),
 (3996, 0.10147651372376076),
 (4128, 0.10147651372376076),
 (541, 0.10138838820672659),
 (2095, 0.10138838820672659),
 (3439, 0.10138838820672659),
 (10, 0.101338918387628),
 (445, 0.101338918387628),
 (650, 0.101338918387628),
 (1610, 0.101338918387628),
 (3150, 0.101338918387628),
 (555, 0.10076376380498041),
 (5, 0.10060545457319173),
 (141, 0.10060545457319173),
 (2435, 0.10060545457319173),
 (535, 0.10012523486435178),
 (3020, 0.10012523486435178),
 (2243, 0.10012523486435176),
 (654, 0.09984038297885897),
 (1530, 0.09984038297885897),
 (2260, 0.09984038297885897),
 (2494, 0.09984038297885897),
 (362, 0.09933992677987831),
 (660, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1154, 0.09933992677987831),
 (1164, 0.09933992677987831),
 (2049, 0.09933992677987831),
 (2558, 0.09933992677987831),
 (2783, 0.09933992677987831),
 (3659, 0.09933992677987831),
 (4479, 0.09933992677987831),
 (845, 0.0993399267798783),
 (2682, 0.09909250441117726),
 (510, 0.0989541391990587),
 (792, 0.0989541391990587),
 (1819, 0.0989541391990587),
 (3009, 0.0989541391990587),
 (203, 0.0978231976089037),
 (480, 0.0978231976089037),
 (1166, 0.0978231976089037),
 (2237, 0.0978231976089037),
 (2552, 0.0978231976089037),
 (3753, 0.0978231976089037),
 (3921, 0.0978231976089037),
 (4092, 0.0978231976089037),
 (4750, 0.0978231976089037),
 (1771, 0.09764582085806336),
 (219, 0.09733285267845754),
 (263, 0.09733285267845754),
 (1025, 0.09733285267845754),
 (1938, 0.09733285267845754),
 (3535, 0.09733285267845754),
 (1471, 0.0967301666813349),
 (3872, 0.0967301666813349),
 (18, 0.09626070358206487),
 (794, 0.09567297464698798),
 (1426, 0.09567297464698798),
 (1688, 0.09567297464698798),
 (246, 0.09558988911273408),
 (167, 0.09544271444636668),
 (244, 0.09544271444636668),
 (256, 0.09544271444636668),
 (1717, 0.09544271444636668),
 (1723, 0.09544271444636668),
 (1880, 0.09544271444636668),
 (2392, 0.09544271444636668),
 (3619, 0.09544271444636668),
 (4020, 0.09544271444636668),
 (363, 0.09493290614465533),
 (4533, 0.09493290614465533),
 (11, 0.09464970485606021),
 (473, 0.09464970485606021),
 (543, 0.09464970485606021),
 (3618, 0.09464970485606021),
 (674, 0.09428928580058928),
 (754, 0.09428928580058928),
 (279, 0.09365858115816941),
 (534, 0.09365858115816941),
 (563, 0.09365858115816941),
 (596, 0.09365858115816941),
 (791, 0.09365858115816941),
 (1066, 0.09365858115816941),
 (1441, 0.09365858115816941),
 (2089, 0.09365858115816941),
 (2646, 0.09365858115816941),
 (2846, 0.09365858115816941),
 (3460, 0.09365858115816941),
 (3734, 0.09365858115816941),
 (3781, 0.09365858115816941),
 (3933, 0.09365858115816941),
 (4191, 0.09365858115816941),
 (157, 0.0936585811581694),
 (230, 0.09365858115816939),
 (785, 0.09365858115816939),
 (51, 0.09304036594559835),
 (491, 0.09304036594559835),
 (271, 0.09269795493186431),
 (410, 0.09269795493186431),
 (587, 0.09269795493186431),
 (23, 0.09197090092274487),
 (148, 0.09197090092274487),
 (1075, 0.09197090092274487),
 (1430, 0.09197090092274487),
 (1566, 0.09197090092274487),
 (1569, 0.09197090092274487),
 (4057, 0.09197090092274487),
 (4196, 0.09197090092274487),
 (4324, 0.09197090092274487),
 (2566, 0.09183979479633061),
 (43, 0.09176629354822471),
 (243, 0.09176629354822471),
 (331, 0.09176629354822471),
 (602, 0.09176629354822471),
 (898, 0.09176629354822471),
 (1453, 0.09176629354822471),
 (1842, 0.09176629354822471),
 (2488, 0.09176629354822471),
 (692, 0.09125667909262308),
 (9, 0.09086217008485092),
 (270, 0.09086217008485092),
 (2588, 0.09086217008485092),
 (2697, 0.09086217008485092),
 (3441, 0.09086217008485092),
 (12, 0.09037128496931669),
 (292, 0.09037128496931669),
 (400, 0.09037128496931669),
 (511, 0.09037128496931669),
 (564, 0.09037128496931669),
 (1257, 0.09037128496931669),
 (1476, 0.09037128496931669),
 (2641, 0.09037128496931669),
 (2647, 0.09037128496931669),
 (2656, 0.09037128496931669),
 (3446, 0.09037128496931669),
 (995, 0.08998425413316952),
 (1270, 0.08998425413316952),
 (2709, 0.08998425413316952),
 (3387, 0.08998425413316952),
 (813, 0.0891313035643173),
 (1796, 0.0891313035643173),
 (2105, 0.0891313035643173),
 (59, 0.08903057122447033),
 (2444, 0.08903057122447033),
 (274, 0.08894313631879691),
 (33, 0.08885233166386385),
 (457, 0.08885233166386385),
 (1627, 0.08885233166386385),
 (2955, 0.08885233166386385),
 (3447, 0.08885233166386385),
 (1779, 0.08830215713766959),
 (1017, 0.08749572785196143),
 (1397, 0.08749572785196143),
 (3554, 0.08749572785196143),
 (799, 0.08746392856766495),
 (2111, 0.08746392856766495),
 (2, 0.08740748201220976),
 (597, 0.08740748201220976),
 (1140, 0.08740748201220976),
 (1239, 0.08740748201220976),
 (2247, 0.08740748201220976),
 (2567, 0.08740748201220976),
 (2864, 0.08740748201220976),
 (3320, 0.08740748201220976),
 (3430, 0.08740748201220976),
 (3547, 0.08740748201220976),
 (206, 0.0870571500132014),
 (1442, 0.08695980950674562),
 (32, 0.08671099695241201),
 (143, 0.08671099695241201),
 (1526, 0.08671099695241201),
 (1660, 0.08671099695241201),
 (1694, 0.08671099695241201),
 (2359, 0.08671099695241201),
 (2852, 0.08671099695241201),
 (3004, 0.08671099695241201),
 (3405, 0.08671099695241201),
 (3718, 0.08671099695241201),
 (4346, 0.08671099695241201),
 (389, 0.08603090020146066),
 (1095, 0.08603090020146066),
 (745, 0.08603090020146065),
 (3133, 0.08603090020146065),
 (4249, 0.08603090020146065),
 (4727, 0.08603090020146065),
 (30, 0.08594700851870801),
 (129, 0.08594700851870801),
 (199, 0.08594700851870801),
 (217, 0.08594700851870801),
 (2736, 0.08594700851870801),
 (618, 0.08520286456846099),
 (718, 0.08520286456846099),
 (1303, 0.08520286456846099),
 (1902, 0.08520286456846099),
 (2966, 0.08520286456846099),
 (3820, 0.08520286456846099),
 (1, 0.08471737420873576),
 (315, 0.08471737420873576),
 (894, 0.08471737420873576),
 (1205, 0.08471737420873576),
 (1304, 0.08471737420873576),
 (2181, 0.08471737420873576),
 (2579, 0.08471737420873576),
 (3354, 0.08471737420873576),
 (4546, 0.08471737420873576),
 (1635, 0.08447772061910234),
 (2350, 0.08447772061910234),
 (2523, 0.08447772061910234),
 (20, 0.08439828691971296),
 (62, 0.0837707816583391),
 (381, 0.0837707816583391),
 (776, 0.0837707816583391),
 (827, 0.0837707816583391),
 (1828, 0.0837707816583391),
 (2335, 0.0837707816583391),
 (3178, 0.0837707816583391),
 (3216, 0.0837707816583391),
 (3975, 0.0837707816583391),
 (164, 0.08346223261119858),
 (227, 0.08346223261119858),
 (626, 0.08346223261119858),
 (787, 0.08346223261119858),
 (878, 0.08346223261119858),
 (1071, 0.08346223261119858),
 (2175, 0.08346223261119858),
 (3299, 0.08346223261119858),
 (48, 0.0830812984794528),
 (403, 0.0830812984794528),
 (2892, 0.0830812984794528),
 (131, 0.08240856434303293),
 (142, 0.08226127456606226),
 (329, 0.08226127456606226),
 (1287, 0.08226127456606226),
 (1745, 0.08226127456606226),
 (1764, 0.08226127456606226),
 (2163, 0.08226127456606226),
 (2657, 0.08226127456606226),
 (3138, 0.08226127456606226),
 (2382, 0.08193419066805777),
 (19, 0.08175191193132876),
 (79, 0.08175191193132876),
 (2199, 0.08175191193132876),
 (45, 0.08111071056538127),
 (245, 0.08111071056538127),
 (349, 0.08111071056538127),
 (455, 0.08111071056538127),
 (584, 0.08111071056538127),
 (866, 0.08111071056538127),
 (929, 0.08111071056538127),
 (1003, 0.08111071056538127),
 (1267, 0.08111071056538127),
 (1274, 0.08111071056538127),
 (1515, 0.08111071056538127),
 (1517, 0.08111071056538127),
 (1743, 0.08111071056538127),
 (2861, 0.08111071056538127),
 (2876, 0.08111071056538127),
 (3468, 0.08111071056538127),
 (3879, 0.08111071056538127),
 (4553, 0.08111071056538127),
 (4619, 0.08111071056538127),
 (63, 0.08048436365855338),
 (153, 0.08048436365855338),
 (486, 0.08031157077540445),
 (39, 0.08000711205939975),
 (96, 0.08000711205939975),
 (242, 0.08000711205939975),
 (547, 0.08000711205939975),
 (854, 0.08000711205939975),
 (901, 0.08000711205939975),
 (922, 0.08000711205939975),
 (1159, 0.08000711205939975),
 (2300, 0.08000711205939975),
 (2640, 0.08000711205939975),
 (2679, 0.08000711205939975),
 (3100, 0.08000711205939975),
 (103, 0.07987230638308718),
 (1922, 0.07987230638308718),
 (2788, 0.07987230638308718),
 (286, 0.0792740035289418),
 (16, 0.07894736842105264),
 (1078, 0.07894736842105264),
 (1323, 0.07894736842105264),
 (2312, 0.07894736842105264),
 (2326, 0.07894736842105264),
 (3162, 0.07894736842105264),
 (3231, 0.07894736842105264),
 (3762, 0.07894736842105264),
 (3849, 0.07894736842105264),
 (4310, 0.07894736842105264),
 (4605, 0.07894736842105264),
 (193, 0.07878168645790681),
 (222, 0.07868894753646337),
 (993, 0.07868894753646337),
 (1321, 0.07868894753646337),
 (1617, 0.07868894753646337),
 (1824, 0.07868894753646337),
 (2667, 0.07868894753646337),
 (2894, 0.07868894753646337),
 (3726, 0.07868894753646337),
 (3985, 0.07868894753646337),
 (4462, 0.07868894753646337),
 (1920, 0.0781166566864507),
 (2287, 0.0781166566864507),
 (112, 0.07792865001991967),
 (241, 0.07792865001991967),
 (402, 0.07792865001991967),
 (720, 0.07792865001991967),
 (955, 0.07792865001991967),
 (1111, 0.07792865001991967),
 (2159, 0.07792865001991967),
 (2215, 0.07792865001991967),
 (3089, 0.07792865001991967),
 (607, 0.07755667343294813),
 (3597, 0.07755667343294813),
 (479, 0.07733602811121826),
 (1655, 0.0770085628656519),
 (207, 0.07694837640638656),
 (365, 0.07694837640638656),
 (2936, 0.07694837640638656),
 (4334, 0.07694837640638656),
 (38, 0.07647191129018727),
 (1028, 0.07647191129018727),
 (1252, 0.07647191129018727),
 (1381, 0.07647191129018727),

In [70]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie ].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:20] # we need first 5 other than the given one
    
    for i in movies_list :
        print(new_df.iloc[i[0]].title)

In [71]:
recommend('Interstellar')

Silent Running
Guardians of the Galaxy
Space Cowboys
Solaris
Apollo 13
Lost in Space
2001: A Space Odyssey
The Right Stuff
Prometheus
Ender's Game
Moonraker
Congo
Zathura: A Space Adventure
A.I. Artificial Intelligence
The Martian
Star Trek Beyond
Gattaca
Armageddon
Jupiter Ascending

In [72]:
import pickle

In [73]:
pickle.dump(new_df,open('movies_genres_revised.pkl','wb'))

In [74]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Newlyweds', 'Signed, Sealed, Delivered', 'My Date with Drew'],
      dtype=object)

In [75]:
pickle.dump(new_df.to_dict(),open('movies_dict_genres_revised.pkl','wb'))

In [76]:
pickle.dump(similarity,open('similarity_genres_revised.pkl','wb'))

In [77]:
#API = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=e3fa2e663af675c73ca11e5f71223360"

In [78]:
extras1 = pd.read_csv("tmdb_5000_movies.csv")
extras2 = pd.read_csv("tmdb_5000_credits.csv")